// <auto-generated />
using System;
using EmployeeManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Payroll"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Admin"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "75 Albin Road St",
                            BarCode = "6776443",
                            DateOfBirth = new DateTime(1980, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "john@ims.com",
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Stanford",
                            PhoneNumber = "0068 586376456",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "57 Crossroad St",
                            BarCode = "6787443",
                            DateOfBirth = new DateTime(1981, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "mary@ims.com",
                            FirstName = "Mary",
                            Gender = 1,
                            LastName = "Crester",
                            PhoneNumber = "0068 123876456",
                            PhotoPath = "images/mary.png"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "33 Jumper Fall St",
                            BarCode = "4632879",
                            DateOfBirth = new DateTime(1973, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "nick@ims.com",
                            FirstName = "Nick",
                            Gender = 0,
                            LastName = "Donovan",
                            PhoneNumber = "0068 586332466",
                            PhotoPath = "images/nick.png"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Address = "21 Alberd Hall",
                            BarCode = "6783432",
                            DateOfBirth = new DateTime(1985, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "saly@ims.com",
                            FirstName = "Saly",
                            Gender = 1,
                            LastName = "Berdnar",
                            PhoneNumber = "0068 223432486",
                            PhotoPath = "images/saly.png"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Address = "98 Horseford Alley",
                            BarCode = "4323654",
                            DateOfBirth = new DateTime(1972, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "steve@ims.com",
                            FirstName = "Steve",
                            Gender = 0,
                            LastName = "Busemi",
                            PhoneNumber = "0068 145333225",
                            PhotoPath = "images/steve.png"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Address = "32 California St",
                            BarCode = "8976542",
                            DateOfBirth = new DateTime(1984, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "brad@ims.com",
                            FirstName = "Brad",
                            Gender = 0,
                            LastName = "Randall",
                            PhoneNumber = "0068 764353653",
                            PhotoPath = "images/brad.png"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Address = "58 Indianna St",
                            BarCode = "2235432",
                            DateOfBirth = new DateTime(1974, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "roger@ims.com",
                            FirstName = "Roger",
                            Gender = 0,
                            LastName = "Fredrig",
                            PhoneNumber = "0068 445743241",
                            PhotoPath = "images/roger.png"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Address = "22 California St",
                            BarCode = "3342224",
                            DateOfBirth = new DateTime(1988, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "teressa@ims.com",
                            FirstName = "Teressa",
                            Gender = 1,
                            LastName = "May",
                            PhoneNumber = "0068 656743233",
                            PhotoPath = "images/teressa.png"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Address = "45 Linard St",
                            BarCode = "3345221",
                            DateOfBirth = new DateTime(1986, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "sara@ims.com",
                            FirstName = "Sara",
                            Gender = 1,
                            LastName = "Jennings",
                            PhoneNumber = "0068 764353653",
                            PhotoPath = "images/sara.png"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Address = "60 Zambata Corn St",
                            BarCode = "9987556",
                            DateOfBirth = new DateTime(1976, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "jack@ims.com",
                            FirstName = "Jack",
                            Gender = 0,
                            LastName = "Pallace",
                            PhoneNumber = "0068 764353653",
                            PhotoPath = "images/moImage.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
